name: my_flutter_project
environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  auto_route: ^10.0.1
  bdd_widget_test: ^1.7.6
  build_runner: ^2.4.13
  dio: ^5.8.0+1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0 
  freezed: ^2.5.7
  get_it: ^8.0.3
  i69n: ^3.0.0
  injectable: ^2.5.0
  json_serializable: ^6.9.0
  retrofit: ^4.4.2
  
dev_dependencies:
  melos: ^6.3.2